### ISSUE TITLE
ファイルの作成とrouteの追加

### ISSUE THREAD

**Issue by Ragamn** [takumiTakahata/equipment_management_system#42]
### PC画面

- [x] #43
- [x] #44
- [x] #46
- [x] #48
- [x] #63
- [x] #62
- [x] #65
- [x] #66
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #102

### スマホ画面

- [x] #45
- [x] #47
- [x] #49
- [x] #51
- [x] #50
- [x] #52
- [x] #53
- [x] #54

**Comment by Raiki215** [comment]
作業完了
